# Introduction to Python and Numpy


We introduce here the Python language. Only the bare minimum
necessary for getting started with Numpy and Scipy is addressed here.
To learn more about the language, consider going through the
excellent tutorial http://www.scipy-lectures.org/intro/index.html. 

The structure of this lecture is:

   - **Part 0**: introduction to Python and Numpy.

   - **Part I**: batch gradient descent, visualize convergence.

   - **Part II**: exercise: accelerated gradient descent, run, check results.

   



## Requirements

To follow this course you will need to have Python with the following libraries: numpy, numba, scipy, matplotlib, jupyter. We will access Python through the [jupyter notebook](http://jupyter.org) interface.

The recommended way to have all the necessary packages is by simply downloading and installing the [Anaconda](https://www.continuum.io/downloads) distribution.

For those that already have Anaconda or Miniconda installed, the aforementioned packages can be installed/updated by typing in the command line

    conda install numpy numba scipy matplotlib




## Introduction

Python is a **programming language**, as are C, Fortran, BASIC, PHP,
etc. Some specific features of Python are as follows:

* an *interpreted* (as opposed to *compiled*) language. Contrary to e.g.
C or Fortran, one does not compile Python code before executing it. In
addition, Python can be used **interactively**: many Python
interpreters are available, from which commands and scripts can be
executed.

* a free software released under an **open-source** license: Python can
be used and distributed free of charge, even for building commercial
software.

* **multi-platform**: Python is available for all major operating
systems, Windows, Linux/Unix, MacOS X, most likely your mobile phone
OS, etc.

* a very readable language with clear non-verbose syntax

* a language for which a large variety of high-quality packages are
available for various applications, from web frameworks to scientific
computing.

* a language very easy to interface with other languages, in particular C
and C++.

* Some other features of the language are illustrated just below. For
example, Python is an object-oriented language, with dynamic typing
(the same variable can contain objects of different types during the
course of a program).


See https://www.python.org/about/ for more information about
distinguishing features of Python.

# Hello world

you type in the cells, execute commands with shift + Enter

```print("Hello world")```

In [ ]:
print("Hello world")

## Floats, Ints, etc.

There contains the basic data types  a floating point type that is created when the variable has decimal values:

    c = 2.1
    type(c)

In [ ]:
c = 2.1

In [ ]:
type(c)

#  Containers

_Tip_: Python provides many efficient types of containers, in which collections of objects can be stored.

## Lists

A list is an ordered collection of objects, that may have different types. For example:


    colors = ['red', 'blue', 'green', 'black', 'white']
    type(colors)

In [ ]:
colors = ['red', 'blue', 'green', 'black', 'white']

In [ ]:
type(colors)

Indexing: accessing individual objects contained in the list::

In [ ]:
colors[2]

<img style="float: left; width: 50px; top: -20px" src="https://cdn1.iconfinder.com/data/icons/hawcons/32/700303-icon-61-warning-128.png" /> WARNING: **Indexing starts at 0** (as in C), not at 1 (as in Fortran or Matlab)

Counting from the end with negative indices:

In [ ]:
colors[-2]

## Slicing: obtaining sublists of regularly-spaced elements


In [ ]:
colors

In [ ]:
colors[1:5:2]

**Slicing syntax**: ``colors[start:stop:stride]``

  _Tip_: All slicing parameters are optional::

In [ ]:
colors

In [ ]:
colors[3:]

In [ ]:
colors[:3]

### Exercise: what is the output of ```colors[::2]```. Why?



In [ ]:
colors[::2]

### Exercise: reverse a list

In [ ]:
colors[::-1]

In [ ]:
s = "asdfdfd"

# Control Flow

Controls the order in which the code is executed.

## if/elif/else

    if 2**2 == 4:
        print('Obvious!')

In [ ]:
s = """asdfadsf
asdfdf
asdfdf
"""

# for/range

Iterating with an index::

    >>> for i in range(4):
    ...     print(i)
    0
    1
    2
    3


In [1]:
for i in range(0, 10, 2):
    print(i)

0
2
4
6
8


But most often, it is more readable to iterate over values::

    >>> for word in ('cool', 'powerful', 'readable'):
    ...     print('Python is %s' % word)
    Python is cool
    Python is powerful
    Python is readable

In [40]:
for word in ['green', 'blue', 'yellow']:
    print(word)

green
blue
yellow



## Blocks are delimited by indentation!

_Tip_: Type the following lines in your Python interpreter, and be careful
to **respect the indentation depth**. The Ipython shell automatically
increases the indentation depth after a colon ``:`` sign; to
decrease the indentation depth, go four spaces to the left with the
Backspace key. Press the Enter key twice to leave the logical block.

    >>> a = 10

    >>> if a == 1:
    ...     print(1)
    ... elif a == 2:
    ...     print(2)
    ... else:
    ...     print('A lot')
    A lot



# Defining functions

### Function definition
    def test():
        print('in test function')

    >>> test()
    in test function

Warning: Function blocks must be indented as other control-flow blocks.



In [2]:
def test():
    print('in test function')

### Return statement

Functions can *optionally* return values.


    >>> def disk_area(radius):
       ...:     return 3.14 * radius * radius
       ...:

    >>> disk_area(1.5)
    >>> 7.0649999999999995

Note: By default, functions return ``None``.

The syntax to define a function:

    * the ``def`` keyword;

    * is followed by the function's **name**, then

    * the arguments of the function are given between parentheses followed
      by a colon.

    * the function body;

    * and ``return object`` for optionally returning values.





### Parameters

Mandatory parameters (positional arguments)


    >>> def double_it(x):
       ....:     return x * 2
       ....:

    >>> double_it(3)
    >>> 6

    >>> double_it()
    ---------------------------------------------------------------------------
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: double_it() takes exactly 1 argument (0 given)

Optional parameters (keyword or named arguments)


    >>> def double_it(x=2):
       ....:     return x * 2
       ....:

    >>> double_it()
    >>> 4

    >>> double_it(3)
    >>> 6

Keyword arguments allow you to specify *default values*.



# The NumPy array object


### What are NumPy and NumPy arrays?

NumPy arrays are


**Python** objects:

  - high-level number objects: integers, floating point

  - containers: lists (costless insertion and append), dictionaries
      (fast lookup)


**NumPy** provides:

  - extension package to Python for multi-dimensional arrays

  - closer to hardware (efficiency)

  - designed for scientific computation (convenience)

  - Also known as *array oriented computing*

In [5]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]



**Why it is useful:** Memory-efficient container that provides fast numerical
operations.

In [7]:
a = range(1000)
%timeit [i**2 for i in L]

1000 loops, best of 3: 337 µs per loop


In [8]:
a = np.arange(1000)
%timeit a**2

The slowest run took 14.89 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.29 µs per loop


## NumPy Reference documentation

- On the web: http://docs.scipy.org/

- Interactive help:

     ```python
     np.array?
     ```


## Creating arrays

### Manual construction of arrays

* **1-D**:

  ```python

    >>> a = np.array([0, 1, 2, 3])
    >>> a
    array([0, 1, 2, 3])
    >>> a.ndim
    1
    >>> a.shape
    (4,)
    >>> len(a)
    4
    ```

* **2-D, 3-D, etc**:

  ```python

    >>> b = np.array([[0, 1, 2], [3, 4, 5]])    # 2 x 3 array
    >>> b
    array([[0, 1, 2],
           [3, 4, 5]])
    >>> b.ndim
    2
    >>> b.shape
    (2, 3)
    >>> len(b)     # returns the size of the first dimension
    2

    >>> c = np.array([[[1], [2]], [[3], [4]]])
    >>> c
    array([[[1],
            [2]],
    <BLANKLINE>
           [[3],
            [4]]])
    >>> c.shape
    (2, 2, 1)
    ```



## Functions for creating arrays

In practice, we rarely enter items one by one...

* Evenly spaced:


    >>> a = np.arange(10) # 0 .. n-1  (!)
    >>> a
    array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    >>> b = np.arange(1, 9, 2) # start, end (exclusive), step
    >>> b
    array([1, 3, 5, 7])

* or by number of points:


    >>> c = np.linspace(0, 1, 6)   # start, end, num-points
    >>> c
    array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ])
    >>> d = np.linspace(0, 1, 5, endpoint=False)
    >>> d
    array([ 0. ,  0.2,  0.4,  0.6,  0.8])

* Common arrays:

    ```
    >>> a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
    >>> a
    array([[ 1.,  1.,  1.],
           [ 1.,  1.,  1.],
           [ 1.,  1.,  1.]])
    >>> b = np.zeros((2, 2))
    >>> b
    array([[ 0.,  0.],
           [ 0.,  0.]])
    >>> c = np.eye(3)
    >>> c
    array([[ 1.,  0.,  0.],
           [ 0.,  1.,  0.],
           [ 0.,  0.,  1.]])
    >>> d = np.diag(np.array([1, 2, 3, 4]))
    >>> d
    array([[1, 0, 0, 0],
           [0, 2, 0, 0],
           [0, 0, 3, 0],
           [0, 0, 0, 4]])
    ```


.. EXE: construct 1 2 3 4 5

.. EXE: construct -5, -4, -3, -2, -1

.. EXE: construct 2 4 6 8

.. EXE: look what is in an empty() array

.. EXE: construct 15 equispaced numbers in range [0, 10]

Basic data types
----------------

You may have noticed that, in some instances, array elements are displayed with
a trailing dot (e.g. ``2.`` vs ``2``). This is due to a difference in the
data-type used:

    >>> a = np.array([1, 2, 3])
    >>> a.dtype
    dtype('int64')

    >>> b = np.array([1., 2., 3.])
    >>> b.dtype
    dtype('float64')

    Different data-types allow us to store data more compactly in memory,
    but most of the time we simply work with floating point numbers.
    Note that, in the example above, NumPy auto-detects the data-type
    from the input.

-----------------------------

You can explicitly specify which data-type you want:

    >>> c = np.array([1, 2, 3], dtype=float)
    >>> c.dtype
    dtype('float64')


The **default** data type is floating point:


    >>> a = np.ones((3, 3))
    >>> a.dtype
    dtype('float64')

There are also other types:

Complex:


        >>> d = np.array([1+2j, 3+4j, 5+6*1j])
        >>> d.dtype
        dtype('complex128')

:Bool:


        >>> e = np.array([True, False, False, True])
        >>> e.dtype
        dtype('bool')

:Strings:


        >>> f = np.array(['Bonjour', 'Hello', 'Hallo',])
        >>> f.dtype     # <--- strings containing max. 7 letters  # doctest: +SKIP
        dtype('S7')

Much more...

    * ``int32``
    * ``int64``
    * ``uint32``
    * ``uint64``

