# Introduction to Python and Numpy


We introduce here the Python language. Only the bare minimum
necessary for getting started with Numpy and Scipy is addressed here.
To learn more about the language, consider going through the
excellent tutorial http://www.scipy-lectures.org/intro/index.html. 

The structure of this lecture is:

   - **Part 0**: introduction to Python and Numpy.

   - **Part I**: batch gradient descent, visualize convergence.

   - **Part II**: exercise: stochastic gradient descent, run, check results.

   



## Requirements

To follow this course you will need to have Python with the following libraries: numpy, numba, scipy, matplotlib, jupyter. We will access Python through the [jupyter notebook](http://jupyter.org) interface.

The recommended way to have all the necessary packages is by simply downloading and installing the [Anaconda](https://www.continuum.io/downloads) distribution.

For those that already have Anaconda or Miniconda installed, the aforementioned packages can be installed/updated by typing in the command line

    conda install numpy numba scipy matplotlib




## Introduction

Python is a **programming language**, as are C, Fortran, BASIC, PHP,
etc. Some specific features of Python are as follows:

* an *interpreted* (as opposed to *compiled*) language. Contrary to e.g.
C or Fortran, one does not compile Python code before executing it. In
addition, Python can be used **interactively**: many Python
interpreters are available, from which commands and scripts can be
executed.

* a very readable language with clear non-verbose syntax

* a language for which a large variety of high-quality packages are
available for various applications, from web frameworks to scientific
computing.

* a language very easy to interface with other languages, in particular C
and C++.



See https://www.python.org/about/ for more information about
distinguishing features of Python.

# Hello world

you type in the cells, execute commands with shift + Enter

```print("Hello world")```

In [1]:
print("Hello world")

Hello world


## Floats, Ints, etc.

There contains the basic data types  a floating point type that is created when the variable has decimal values:

    c = 2.1
    type(c)

In [2]:
c = 2.1

In [3]:
type(c)

float

#  Containers

_Tip_: Python provides many efficient types of containers, in which collections of objects can be stored.

## Lists

A list is an ordered collection of objects, that may have different types. For example:


    colors = ['red', 'blue', 'green', 'black', 'white']
    type(colors)

In [4]:
colors = ['red', 'blue', 'green', 'black', 'white']

In [5]:
type(colors)

list

Indexing: accessing individual objects contained in the list::

In [6]:
colors[2]

'green'

<img style="float: left; width: 50px; top: -20px" src="https://cdn1.iconfinder.com/data/icons/hawcons/32/700303-icon-61-warning-128.png" /> WARNING: **Indexing starts at 0** (as in C), not at 1 (as in Fortran or Matlab)

Counting from the end with negative indices:

In [8]:
colors[-2]

'black'

## Slicing: obtaining sublists of regularly-spaced elements


In [9]:
colors

['red', 'blue', 'green', 'black', 'white']

In [10]:
colors[1:5:2]

['blue', 'black']

**Slicing syntax**: ``colors[start:stop:stride]``

  _Tip_: All slicing parameters are optional::

In [11]:
colors

['red', 'blue', 'green', 'black', 'white']

In [12]:
colors[3:]

['black', 'white']

In [13]:
colors[:3]

['red', 'blue', 'green']

### Exercise: what is the output of ```colors[::2]```. Why?



In [14]:
colors[::2]

['red', 'green', 'white']

### Exercise: reverse a list

In [15]:
colors[::-1]

['white', 'black', 'green', 'blue', 'red']

In [16]:
s = "hello"

In [17]:
s[::-1]

'olleh'

# Control Flow

Controls the order in which the code is executed.

## if/elif/else



In [20]:
if 2**2 == 5:
    print('Obvious!')
else:
    print('No')

No


# for/range

Iterating with an index::

    >>> for i in range(4):
    ...     print(i)
    0
    1
    2
    3


In [24]:
for i in range(0, 10, 2):
   print(i)

0
2
4
6
8


But most often, it is more readable to iterate over values::

    >>> for word in ('cool', 'powerful', 'readable'):
    ...     print('Python is %s' % word)
    Python is cool
    Python is powerful
    Python is readable

In [25]:
for word in ['green', 'blue', 'yellow']:
    print(word)

green
blue
yellow



## Blocks are delimited by indentation!

_Tip_: Type the following lines in your Python interpreter, and be careful
to **respect the indentation depth**. The Ipython notebook automatically
increases the indentation depth after a colon ``:`` sign; to
decrease the indentation depth, go four spaces to the left with the
Backspace key. Press the Enter key twice to leave the logical block.

    >>> a = 10

    >>> if a == 1:
    ...     print(1)
    ... elif a == 2:
    ...     print(2)
    ... else:
    ...     print('A lot')
    A lot



# Defining functions

### Function definition
    def test():
        print('in test function')

    >>> test()
    in test function

Warning: Function blocks must be indented as other control-flow blocks.



In [26]:
def test():
    print('in test function')

In [27]:
test()

in test function


### Return statement

Functions can *optionally* return values.


    >>> def disk_area(radius):
       ...:     return 3.14 * radius * radius
       ...:

    >>> disk_area(1.5)
    >>> 7.0649999999999995

Note: By default, functions return ``None``.

The syntax to define a function:

    * the ``def`` keyword;

    * is followed by the function's **name**, then

    * the arguments of the function are given between parentheses followed
      by a colon.

    * the function body;

    * and ``return object`` for optionally returning values.





### Parameters

* Mandatory parameters (positional arguments)

* Optional parameters (keyword arguments)

Keyword arguments allow you to specify *default values*.


In [28]:
# this is a positional argument
def double_it(x):
    return x * x


In [30]:
double_it(-2.)

4.0

### Exercise (5 min)

  * Define a function that computes the n-th Fibonacci number

In [31]:
def fib(n):
    if n == 1:
        return 1
    elif n == 2:
        return 1
    return fib(n-1) + fib(n-2)

In [36]:
for i in range(1, 20):
    print(fib(i))

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181


In [39]:
fib(20)

6765


# The NumPy array object


### What are NumPy and NumPy arrays?

**NumPy** provides:

  - extension package to Python for multi-dimensional arrays

  - closer to hardware (efficiency)

  - designed for scientific computation (convenience)


In [42]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]



**Why it is useful:** Memory-efficient container that provides fast numerical
operations.

In [43]:
a = range(1000)
%timeit [i**2 for i in a]

1000 loops, best of 3: 301 µs per loop


In [44]:
a = np.arange(1000)
%timeit a**2

The slowest run took 25.79 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.03 µs per loop


## NumPy Reference documentation

- On the web: http://docs.scipy.org/

- Interactive help:

     ```python
     np.array?
     ```


In [46]:
np.array?

## Creating arrays

### Manual construction of arrays

np.array(...)


In [47]:
np.array([1, 2, 3])

array([1, 2, 3])


## Functions for creating arrays

In practice, we rarely enter items one by one...

* Evenly spaced: np.arange(start, end, step)


* or by number of points: np.linspace(start, end, num_points)


* Common arrays: np.ones, np.zeros, np.eye, np.diag



In [48]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.linspace(0, 10, 10)

array([  0.        ,   1.11111111,   2.22222222,   3.33333333,
         4.44444444,   5.55555556,   6.66666667,   7.77777778,
         8.88888889,  10.        ])

In [51]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [57]:
b = np.zeros(10)
print(b.shape)

(10,)


In [56]:
a = np.eye(3)
print(a.shape)

(3, 3)


In [60]:
np.diag(1, 1, 1)

TypeError: diag() takes from 1 to 2 positional arguments but 3 were given

In [61]:
np.diag((1, 1, 1))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Exercises (10 min)

.. EXE: construct 1 2 3 4 5

.. EXE: construct -5, -4, -3, -2, -1

.. EXE: construct 2 4 6 8

.. EXE: look what is in an empty() array

.. EXE: construct 15 equispaced numbers in range [0, 10]

In [73]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [74]:
a[0] = 1.2

In [75]:
a

array([1, 1, 2, 3, 4])

In [69]:
b = np.empty(10)
print(b.dtype)

float64


Basic data types
----------------

You may have noticed that, in some instances, array elements are displayed with
a trailing dot (e.g. ``2.`` vs ``2``). This is due to a difference in the
data-type used.


Different data-types allow us to store data more compactly in memory,
but most of the time we simply work with floating point numbers.
Note that, in the example above, NumPy auto-detects the data-type
from the input.


The **default** data type is floating point